# Generated by Django 3.0.8 on 2020-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discusscomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discusspost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
